const documentList = [
    {
        id: 1,
        name: "diploma.docx",
        number: "1689",
        status: "Lorem ipsum",
        version: "2",
        author: "Marko Markovic",
        type: "Lorem ipsum",
        date: "25.03.2021.",
        effectiveNumber: "01/2-23/1-19",
        description: "Lorem Lorem Ipsum Ipsum",
        subject: "Loreeeeeeeeem",
        documentSign: "01/2-23/1-19",
        receptionMode: "Ipsuuuuuuum",
        issueCity: "PG",
        senderDocNumber: "01/2-23/1-19",
        senderDocDate: "12.01.2020."
    },
    {
        id: 2,
        name: "knjiga.pdf",
        number: "3689",
        status: "Lorem ipsum",
        version: "2",
        author: "Marko Markovic",
        type: "Lorem ipsum",
        date: "25.03.2021.",
        effectiveNumber: "01/2-23/1-19",
        description: "Lorem Lorem Ipsum Ipsum",
        subject: "Loreeeeeeeeem",
        documentSign: "01/2-23/1-19",
        receptionMode: "Ipsuuuuuuum",
        issueCity: "PG",
        senderDocNumber: "01/2-23/1-19",
        senderDocDate: "12.01.2020."
    },
    {
        id: 3,
        name: "tabela.xslx",
        number: "4689",
        status: "Lorem ipsum",
        version: "2",
        author: "Marko Markovic",
        type: "Lorem ipsum",
        date: "25.03.2021.",
        effectiveNumber: "01/2-23/1-19",
        description: "Lorem Lorem Ipsum Ipsum",
        subject: "Loreeeeeeeeem",
        documentSign: "01/2-23/1-19",
        receptionMode: "Ipsuuuuuuum",
        issueCity: "PG",
        senderDocNumber: "01/2-23/1-19",
        senderDocDate: "12.01.2020."
    },
    {
        id: 4,
        name: "diploma2.doc",
        number: "5689",
        status: "Lorem ipsum",
        version: "2",
        author: "Marko Markovic",
        type: "Lorem ipsum",
        date: "25.03.2021.",
        effectiveNumber: "01/2-23/1-19",
        description: "Lorem Lorem Ipsum Ipsum",
        subject: "Loreeeeeeeeem",
        documentSign: "01/2-23/1-19",
        receptionMode: "Ipsuuuuuuum",
        issueCity: "PG",
        senderDocNumber: "01/2-23/1-19",
        senderDocDate: "12.01.2020."
    },
    {
        id: 5,
        name: "tabela2.xsl",
        number: "6689",
        status: "Lorem ipsum",
        version: "2",
        author: "Marko Markovic",
        type: "Lorem ipsum",
        date: "25.03.2021.",
        effectiveNumber: "01/2-23/1-19",
        description: "Lorem Lorem Ipsum Ipsum",
        subject: "Loreeeeeeeeem",
        documentSign: "01/2-23/1-19",
        receptionMode: "Ipsuuuuuuum",
        issueCity: "PG",
        senderDocNumber: "01/2-23/1-19",
        senderDocDate: "12.01.2020."
    },
    {
        id: 6,
        name: "prezentacija2.ppt",
        number: "7689",
        status: "Lorem ipsum",
        version: "2",
        author: "Marko Markovic",
        type: "Lorem ipsum",
        date: "25.03.2021.",
        effectiveNumber: "01/2-23/1-19",
        description: "Lorem Lorem Ipsum Ipsum",
        subject: "Loreeeeeeeeem",
        documentSign: "01/2-23/1-19",
        receptionMode: "Ipsuuuuuuum",
        issueCity: "PG",
        senderDocNumber: "01/2-23/1-19",
        senderDocDate: "12.01.2020."
    },
    {
        id: 7,
        name: "recepti od babe.docx",
        number: "10000",
        status: "U upotrebi",
        version: "1",
        author: "Slaven Ranisavljevic",
        type: "Tekstualni dokument",
        date: "25.03.2022.",
        effectiveNumber: "2/5-0/3-2/2",
        description: "Recepti koje je moja baka najvise upotrebljavala",
        subject: "Ja",
        documentSign: "2/5-0/3-2/2",
        receptionMode: "E-mail",
        issueCity: "PG",
        senderDocNumber: "2/5-0/3-2/2",
        senderDocDate: "12.01.2020."
    },
    {
        id: 8,
        name: "prezentacija.pptx",
        number: "2689",
        status: "Lorem ipsum",
        version: "2",
        author: "Marko Markovic",
        type: "Lorem ipsum",
        date: "25.03.2021.",
        effectiveNumber: "01/2-23/1-19",
        description: "Lorem Lorem Ipsum Ipsum",
        subject: "Loreeeeeeeeem",
        documentSign: "01/2-23/1-19",
        receptionMode: "Ipsuuuuuuum",
        issueCity: "PG",
        senderDocNumber: "01/2-23/1-19",
        senderDocDate: "12.01.2020."
    },
]

export default documentList;